sudo: required
services:
  - docker

before_install: 
  - docker build -t dhavalpandya132/docker-react -f Dockerfile.dev .

script:
  - docker run dhavalpandya132/docker-react npm run test -- --coverage 