sudo: required
services:
  - docker

before_install: 
  - docker build -t dhavalpandya132/docker-react -f ./frontend/Dockerfile.dev ./frontend/

script:
  - docker run -e CI=true dhavalpandya132/docker-react npm run test -- --coverage 